### ISSUE TITLE
CI Setup Options

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger-labs/blockchain-integration-framework#13]
Every branch/PR should be hooked up with CI automatically so that contributors get feedback about their proposed changes without maintainer dependencies.  

Look into the following options as a minimum: 
- [ ] Any CI providers out there who do sponsorships (there’s a bunch of them but we need containers which may cull the herd a bit) 
- [ ] Pre-existing test nets
- [ ] Anything Hyperledger has? Most likely not, resources are only assigned to graduated projects. 
- [ ] Could set up something manually on a cheap VPS provider (e.g. none of the big-name cloud providers) Example: https://www.wishosting.com/order/config/index/VPS/?group_id=2&pricing_id=112

**Comment by petermetz** [comment]
Travis seems to work well enough to warrant no further effort. Closing this for now. 
Can bring up the topic again if we hit a previously unknown limitation in Travis that makes it a no-go.
