### ISSUE TITLE
Ubuntu VM Resource leakage

### ISSUE THREAD

**Issue by jonathan-m-hamilton** [hyperledger-labs/blockchain-integration-framework#14]
Set up the simple-assert-transfer example with all the containers running on the same ubuntu 1804 vm. One of the JVM processes took 100% on all 8 CPU cores and filled up the ram in a couple hours of operation.

**Comment by denis-yu-glotov** [comment]
I am running our current Quorum network (v2.1.1, 4 nodes) for 16 hours at Ubuntu 16.04 vm with 4 cpu and 6 Gb RAM. Now `htop` shows that CPU cores are uniformly 10-40% busy (with spikes to 70%). Memory consumption is 1.87 - 1.92 Gb and stays constantly in this range.
Going to try the latest Quorum (v2.3.0) sample-network to see if it is less resource-greedy.

**Comment by denis-yu-glotov** [comment]
For Quorum v2.3.0, 4 nodes, same other factors, after 45 minutes of running I see memory consumption 1.55 - 1.7 Gb, CPU cores are busy for 20-70% uniformly.

**Comment by petermetz** [comment]
Thank you for the investigation @denis-yu-glotov 
Issue must be on my side. Best guess is that it's specific to how Hyper-V manages RAM for the VM.
For me RAM usage shoots up to 20+GB in a matter of minutes just by having `npm run corda` and the CPUs are pegged at a solid 100% usage constantly. Will try to look for other culprits in my own setup, but it's clear that Corda is not at fault.

**Comment by denis-yu-glotov** [comment]
Final note about Qorda 2.3.0 after 20 hours, memory consumption is 1.67 - 1.72 Gb. So from this side, it is not significantly better, then our current Quorum 2.1.1. Although I noticed that `tessera` has started significantly faster then ours. So it is good to upgrade although not a first priority.
