### ISSUE TITLE
Support NodeJS 10.x, 12.x

### ISSUE THREAD

**Issue by petermetz** [hyperledger-labs/blockchain-integration-framework#29]
The current LTS NodeJS versions should always be supported in general.

Need to have the CI set up before we can move with this. For the CI progress watch: https://github.com/hyperledger-labs/blockchain-integration-framework/issues/13

**Comment by petermetz** [comment]
Might be also blocked by ZeroMQ:
https://github.com/JustinTulloss/zeromq.node/issues/603

**Comment by blefevre** [comment]
Fabric tests are failing under Node 10.
Per https://github.com/grpc/grpc-node/issues/801 certs with `ExtKeyUsageAny` set are now rejected by OpenSSL 1.1.0.
This is fixed in https://github.com/hyperledger/fabric/commit/3c0d63c, but we'll have to regenerate our crypto.
