### ISSUE TITLE
WalletProxy.sol does not appear to be in the repo

### ISSUE THREAD

**Issue by drinkcoffee** [hyperledger-labs/blockchain-integration-framework#37]
In https://github.com/hyperledger-labs/blockchain-integration-framework/blob/master/src/pluggins/contracts/quorum/Root.sol, "contract Root is WalletProxy". The import implies WalletProxy is in the same directory. However, WalletProxy.sol is not in the directory.

**Comment by petermetz** [comment]
Thank you @drinkcoffee 

cc: @hugo-borne

**Comment by petermetz** [comment]
Reproduced when
`Compiling using default compiler, solidity version: 0.5.11+commit.c082d0b4.Emscripten.clang`
