### ISSUE TITLE
CI Logging Enhancement

### ISSUE THREAD

**Issue by petermetz** [hyperledger-labs/blockchain-integration-framework#73]
### Description
As a contributor I want to be able to run CI locally on any Ubuntu host and to be easy to deal with CI and investigate issues at the same time so that I don't spend a lot of time scrolling through logs, but when I do need the logs for certain issues they are always available (all of them, including network logs).

(add more description and relevant links)

### Acceptance Criteria
1. *All* logs (network, validator, api, etc.) are available when needed
2. Logs are easy to skim through instead of having megabytes of text in one chunk
3. 100% Equivalent CI script can be executed on any Ubuntu 18.04 host not just on Travis

**Comment by petermetz** [comment]
If we move the ci.sh commands straight up to the travis yml then we lose acceptance criteria 3)
If we just dump all the logs for every CI run then acceptance criteria 2 may suffer.

**Comment by petermetz** [comment]
Idea: separate logging into it's own concern by using a free provider or OSS sponsorship:
For example this may have a good free plan: https://docs.logentries.com/docs/linux-agent

**Comment by petermetz** [comment]
#74

**Comment by denis-yu-glotov** [comment]
Looks uploading artifacts (build logs that we care about) to Google Firebase is a good option https://docs.travis-ci.com/user/deployment/firebase/.
